<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class _43_kabupaten_model extends CI_Model
{

    public $table = 't43_kabupaten';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        // $this->db->like('id', $q);
    	// $this->db->or_like('provinsi_id', $q);
    	// $this->db->or_like('nama', $q);
    	// $this->db->from($this->table);
        $this->db->like($this->table.'.id', $q);
    	$this->db->or_like('provinsi_id', $q);
    	$this->db->or_like($this->table.'.nama', $q);
        $this->db->or_like('t42_provinsi'.'.nama', $q);
        $this->db->select($this->table . '.*, t42_provinsi.nama as namaProvinsi');
        $this->db->from($this->table);
        $this->db->join('t42_provinsi', 't42_provinsi.id = '.$this->table.'.provinsi_id');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like($this->table.'.id', $q);
    	$this->db->or_like('provinsi_id', $q);
    	$this->db->or_like($this->table.'.nama', $q);
        $this->db->or_like('t42_provinsi'.'.nama', $q);
    	$this->db->limit($limit, $start);
        $this->db->select($this->table . '.*, t42_provinsi.nama as namaProvinsi');
        $this->db->from($this->table);
        $this->db->join('t42_provinsi', 't42_provinsi.id = '.$this->table.'.provinsi_id'); // echo $this->db->get_compiled_select();
        return $this->db->get()->result();
        // return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file _43_kabupaten_model.php */
/* Location: ./application/models/_43_kabupaten_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-03-12 16:47:21 */
/* http://harviacode.com */
