<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class _06_penduduk_model extends CI_Model
{

    public $table = 't06_penduduk';
    public $id = 'idpenduduk';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        // $this->db->where($this->id, $id);
        // return $this->db->get($this->table)->row();
        $this->db->where($this->id, $id);
        $this->db->select($this->table . '.*');
        $this->db->select('t43_kabupaten.nama as namaKabupaten');
        $this->db->select('t41_agama.Agama as namaAgama');
        $this->db->select('t40_pendidikan.Pendidikan as namaPendidikan');
        $this->db->from($this->table);
        $this->db->join('t43_kabupaten', 't43_kabupaten.id = '.$this->table.'.TempatLahir');
        $this->db->join('t41_agama', 't41_agama.idagama = '.$this->table.'.Agama');
        $this->db->join('t40_pendidikan', 't40_pendidikan.idpendidikan = '.$this->table.'.Pendidikan');
        return $this->db->get()->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idpenduduk', $q);
	$this->db->or_like('NoUrut', $q);
	$this->db->or_like('Nama', $q);
	$this->db->or_like('NIK', $q);
	$this->db->or_like('JenisKelamin', $q);
	$this->db->or_like('TempatLahir', $q);
	$this->db->or_like('TanggalLahir', $q);
	$this->db->or_like('Agama', $q);
	$this->db->or_like('Pendidikan', $q);
	$this->db->or_like('Pekerjaan', $q);
	$this->db->or_like('StatusKawin', $q);
	$this->db->or_like('HubunganKeluarga', $q);
	$this->db->or_like('WargaNegara', $q);
	$this->db->or_like('NoPaspor', $q);
	$this->db->or_like('NoKitasKitap', $q);
	$this->db->or_like('NamaAyah', $q);
	$this->db->or_like('NamaIbu', $q);
	$this->db->or_like('idinduk', $q);
	$this->db->or_like('idkk', $q);
	$this->db->or_like('iduser', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idpenduduk', $q);
	$this->db->or_like('NoUrut', $q);
	$this->db->or_like('Nama', $q);
	$this->db->or_like('NIK', $q);
	$this->db->or_like('JenisKelamin', $q);
	$this->db->or_like('TempatLahir', $q);
	$this->db->or_like('TanggalLahir', $q);
	$this->db->or_like('Agama', $q);
	$this->db->or_like('Pendidikan', $q);
	$this->db->or_like('Pekerjaan', $q);
	$this->db->or_like('StatusKawin', $q);
	$this->db->or_like('HubunganKeluarga', $q);
	$this->db->or_like('WargaNegara', $q);
	$this->db->or_like('NoPaspor', $q);
	$this->db->or_like('NoKitasKitap', $q);
	$this->db->or_like('NamaAyah', $q);
	$this->db->or_like('NamaIbu', $q);
	$this->db->or_like('idinduk', $q);
	$this->db->or_like('idkk', $q);
	$this->db->or_like('iduser', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file _06_penduduk_model.php */
/* Location: ./application/models/_06_penduduk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-03-12 11:02:46 */
/* http://harviacode.com */
